kind: BuildConfig
apiVersion: v1
metadata:
    name: "${MICROSERVICE_NAME}"
    labels:
        app: "${MICROSERVICE_NAME}"
        template: "template-nodejs"
spec:
    output:
        to:
            kind: "ImageStreamTag"
            name: "${MICROSERVICE_NAME}:dev"
    source:
        git:
            ref: dev
            uri: '${SOURCE_REPOSITORY_URL}'
        secrets:
            - secret:
                name: npmrc-artifactory-fr
        sourceSecret:
            name: '${SSH_SECRET}'
        type: Git
    strategy:
        sourceStrategy:
            from:
                kind: ImageStreamTag
                name: "nodejs-8-rhel7:latest"
                namespace: "${NAMESPACE}"
            type: Source
    triggers:
        - type: ConfigChangeS
